'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Website.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;C:\Program Files (x86)\NSIS\makensis.exe&quot;  /NOTIFYHWND 1640592  &quot;$(SolutionDir)NSIS Installer\Installer\Main installer.nsi&quot;.
        '''</summary>
        Friend ReadOnly Property PostBuild1() As String
            Get
                Return ResourceManager.GetString("PostBuild1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;C:\Program Files\TortoiseSVN\bin\SubWCRev.exe&quot; &quot;$(SolutionDir)Website&quot; &quot;$(ProjectDir)My Project\AssemblyInfo_temp.vb&quot; &quot;$(ProjectDir)My Project\AssemblyInfo.vb&quot;
        '''
        '''&quot;C:\Program Files\TortoiseSVN\bin\SubWCRev.exe&quot; &quot;$(SolutionDir)Website&quot; &quot;$(SolutionDir)NSIS Installer\Installer\Definitions\ProductDetails_temp.nsh&quot; &quot;$(SolutionDir)NSIS Installer\Installer\Definitions\ProductDetails.nsh&quot;
        '''
        '''%WINDIR%\SYSTEM32\CScript //NoLogo &quot;$(SolutionDir)NSIS Installer\Include\ListFiles.vbs&quot; &quot;$(SolutionDir)NSIS Installer\Includ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PreBuild1() As String
            Get
                Return ResourceManager.GetString("PreBuild1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
