!define PRODUCT_NAME "iPiMP"
!define PRODUCT_VERSION "$BUILD$.$WCREV$"
!define PRODUCT_PUBLISHER "Cheezey"
!define PRODUCT_WEB_SITE "http://http://code.google.com/p/ipimp/"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
