
  SetOutPath "$INSTDIR\mtn"
  File "..\Include\Utilities\mtn\avcodec-51.dll"
  File "..\Include\Utilities\mtn\avdevice-52.dll"
  File "..\Include\Utilities\mtn\avformat-52.dll"
  File "..\Include\Utilities\mtn\avutil-49.dll"
  File "..\Include\Utilities\mtn\bgd.dll"
  File "..\Include\Utilities\mtn\changelog.txt"
  File "..\Include\Utilities\mtn\gpl-2.0.txt"
  File "..\Include\Utilities\mtn\mtn.exe"
  File "..\Include\Utilities\mtn\readme.txt"
  File "..\Include\Utilities\mtn\swscale-0.dll"
  File "..\Include\Utilities\mtn\todo.txt"

  SetOutPath "$INSTDIR\mtn\doc"
  File "..\Include\Utilities\mtn\doc\changelog.txt"
  File "..\Include\Utilities\mtn\doc\index.en.html"
  File "..\Include\Utilities\mtn\doc\todo.txt"
  File "..\Include\Utilities\mtn\doc\usage.en.html"

  SetOutPath "$INSTDIR\mtn\doc\img"
  File "..\Include\Utilities\mtn\doc\img\10000_bc-tlr1_h480_D.jpg"
  File "..\Include\Utilities\mtn\doc\img\10000_bc-tlr1_h480_s.jpg"
  File "..\Include\Utilities\mtn\doc\img\10000_bc-tlr1_h480_V.jpg"
  File "..\Include\Utilities\mtn\doc\img\37084131_b.5_s.jpg"
  File "..\Include\Utilities\mtn\doc\img\37084131_b2_s.jpg"
  File "..\Include\Utilities\mtn\doc\img\40660182_h1.jpg"
  File "..\Include\Utilities\mtn\doc\img\40660182_h100.jpg"
  File "..\Include\Utilities\mtn\doc\img\gt_ps_premiere_2007_FFFFF00_10.jpg"
  File "..\Include\Utilities\mtn\doc\img\gt_ps_premiere_2007_FFFFF00_8_comicbd.ttf_ff0000_00ff00_12.jpg"
  File "..\Include\Utilities\mtn\doc\img\gt_ps_premiere_2007_L1_3.jpg"
  File "..\Include\Utilities\mtn\doc\img\supremecommander_e32006_s.jpg"
  File "..\Include\Utilities\mtn\doc\img\unicode_filename.jpg"

  SetOutPath "$INSTDIR\mtn\src"
  File "..\Include\Utilities\mtn\src\fake_tchar.h"
  File "..\Include\Utilities\mtn\src\gpl-2.0.txt"
  File "..\Include\Utilities\mtn\src\Makefile"
  File "..\Include\Utilities\mtn\src\Makefile.linux"
  File "..\Include\Utilities\mtn\src\Makefile.mingw"
  File "..\Include\Utilities\mtn\src\mtn.c"
