!define PRODUCT_NAME "iPiMP"
!define PRODUCT_VERSION "4.0.1.$WCREV$"
!define PRODUCT_PUBLISHER "Cheezey"
!define PRODUCT_WEB_SITE "http://www.team-mediaportal.com/manual/Extensions-TV-Server-Plugins/iPiMP"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
